version: "2"

services:
  bot:
    build: .
    command: bash -c "npm run postinstall && npm start"
    volumes:
      - ./dist:/rootbear/dist
      - ./config:/rootbear/config
    ports:
      - "9222:9222"
